In [1]:
pwd

'C:\\Users\\Cesar Hooper\\Desktop\\github\\proyecto_MARCELO\\DOCUMENTO'

In [1]:
ls

 O volume na unidade C ‚ Windows
 O N£mero de S‚rie do Volume ‚ B847-75B0

 Pasta de C:\Users\Cesar Hooper\Desktop\github\proyecto_MARCELO\DOCUMENTO

02/03/2023  16:53    <DIR>          .
02/03/2023  16:53    <DIR>          ..
25/02/2023  08:14    <DIR>          .ipynb_checkpoints
25/02/2023  08:59             2.150 Documento - Marcelo.ipynb
25/02/2023  09:03           320.360 Documento.odt
25/02/2023  09:28           232.567 Documento.pdf
24/02/2023  19:07           143.938 imagen1.png
02/03/2023  16:53        24.009.838 modelo_enero2022.pkl
24/02/2023  20:01            34.834 navegador1.png
24/02/2023  20:29            19.277 navegador2.png
24/02/2023  19:20            33.723 prompt.png
25/02/2023  09:27            54.756 pwd.png
               9 arquivo(s)     24.851.443 bytes
               3 pasta(s)   11.836.665.856 bytes dispon¡veis


## Cargando el Modelo

In [9]:
# importando joblib. 
import joblib 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Cargando el modelo
modelo = joblib.load('modelo_enero2022.pkl')

### Generando el camino para traer los archivos, via comandos
Estos pasos nos permiten traer los archivos xlsx desde donde sea que estén. 

In [13]:
# OJO: con el back-slash:
# path ='C:\Users\Cesar Hooper\Desktop\github\proyecto_MARCELO/'

# cambiar backslash para slash
path ='C:/Users/Cesar Hooper/Desktop/.../proyecto_MARCELO/'

In [17]:
# cargando datos los datos de febrero 2022.
datos = pd.read_excel(path + 'DBMLJAN22.xlsx')

In [64]:
datos.head(10)

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0        NaT        NaN        NaN        NaN        NaN        NaN   
1        NaT        NaN        NaN        NaN        NaN        NaN   
2        NaT        NaN        NaN        NaN        NaN        NaN   
3        NaT        NaN        NaN        NaN        NaN        NaN   
4        NaT        NaN        NaN        NaN        NaN        NaN   
5        NaT       hora  LSOI 5min  LSOI S 30     LSOI 4     LSOI D   
6 2022-01-03      10:20          5          9         11         16   
7 2022-01-03      10:21          3          9         11         16   
8 2022-01-03      10:22          3          9         11         16   
9 2022-01-03      10:23          3          9         11         16   

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN   
1        NaN        NaN        NaN        NaN         NaN         NaN   
2        NaN        NaN        NaN        NaN         NaN         NaN   
3        NaN        NaN        NaN        NaN         NaN         NaN   
4        NaN        NaN        NaN        NaN         NaN         NaN   
5     5 min      30 min       4 hr        Day       CCI 5      CCI 30   
6         19         21         25         28          31          33   
7         19         21         25         28          31          33   
8         19         21         25         28          31          33   
9         19         21         25         28          31          33   

  Unnamed: 12 Unnamed: 13 Unnamed: 14   Unnamed: 15            Unnamed: 16  
0         NaN         NaN         NaN           NaN                    NaN  
1         NaN         NaN         NaN           NaN                    NaN  
2         NaN         NaN         NaN           NaN       TENDENCIA ALZA=1  
3         NaN         NaN         NaN           NaN  TENDENCIA A LA BAJA=2  
4         NaN         NaN         NaN           NaN       SIN TENDENCIA=0O  
5      PRECIO        CCI5       CCI30  RETORNOS/MIN             Tendencias  
6     4768.75         -30        -155           NaN                      0  
7        4766         -43        -164         -2.75                      0  
8     4766.75         -44        -161            -2                      0  
9     4768.75         -38        -155             0                      0

In [62]:
# comandos para quitar fecha, hora y eliminar NaN
dataset = datos.dropna().copy()
fecha = dataset['Unnamed: 0']
hora = dataset['Unnamed: 1']
target = dataset['Unnamed: 16'] # cargué datos con clasificación
dataset = dataset.drop(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 16'], axis=1)


Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
7           3          9         11         16         19         21   
8           3          9         11         16         19         21   
9           3          9         11         16         19         21   
10          3          9         11         16         18         21   
11          2          9         11         16         18         21   

   Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
7          25         28          31          33        4766         -43   
8          25         28          31          33     4766.75         -44   
9          25         28          31          33     4768.75         -38   
10         25         27          31          33      4771.5         -30   
11         25         27          30          33     4775.25          14   

   Unnamed: 14 Unnamed: 15  
7         -164       -2.75  
8         -161          -2  
9         -155           0  
10        -145        2.75  
11        -126         6.5

In [67]:
# con el comando shape comprobamos que los datos tienen el formato de 14 columnas y la misma cantidad de filas
dataset.shape, target.shape, fecha.shape, hora.shape

((9931, 14), (9931,), (9931,), (9931,))

In [68]:
# randomizamos los datos
dataset_randomized = dataset.sample(frac=1)
dataset_randomized.head()

Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
8470          5          6         10         15         19         21   
9142          5          6         10         17         19         21   
9465          2          6         11         14         18         22   
101           5          7         13         16         18         22   
5567          2          9         10         15         19         21   

     Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
8470         24         27          30          32     4374.25         126   
9142         24         27          30          32      4353.5         148   
9465         25         28          31          33     4406.25         -24   
101          25         28          31          33      4763.5         -45   
5567         25         27          30          32        4584          19   

     Unnamed: 14 Unnamed: 15  
8470         116      -394.5  
9142         125     -415.25  
9465        -145      -362.5  
101         -159       -5.25  
5567         114     -184.75

In [69]:
# importando librería para normalización de datos
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#  (fiteamos) los datos randomizados
scaler.fit(dataset_randomized)

StandardScaler()

In [70]:
# normalización de los datos no randomizados
dataset_normalized = scaler.transform(dataset)
dataset_normalized

array([[-0.28470634,  1.29439514, -0.18305857, ..., -0.31207686,
        -1.00349502,  1.40903243],
       [-0.28470634,  1.29439514, -0.18305857, ..., -0.32088118,
        -0.98054784,  1.41379375],
       [-0.28470634,  1.29439514, -0.18305857, ..., -0.26805526,
        -0.93465347,  1.42649062],
       ...,
       [-0.28470634, -0.34910523, -1.0711654 , ...,  0.00487868,
         0.92406833, -0.34154848],
       [-0.28470634, -0.34910523, -1.0711654 , ..., -0.00392564,
         0.91641927, -0.34313559],
       [-0.28470634, -0.34910523, -1.0711654 , ...,  0.00487868,
         0.92406833, -0.33996137]])

In [71]:
# aplicación modelo sobre los datos limpios y normalizados.
# recordar que el modelo se cargó con el nombre de modelo

# este comando entrega el resultado de la clasificación -1, 0 ó 1
y_pred = modelo.predict(dataset_normalized)

# este comando entrega la probabilidad de cada resultado
y_proba = modelo.predict_proba(dataset_normalized)

In [75]:
# verificamos dimensiones de los resultados
# lo importante es que tengan misma cantidad de filas.
y_pred.shape, y_proba.shape

((9931,), (9931, 3))

In [76]:
# estos son los resultados de la clasificación
y_pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [48]:
# resultado de las probabilidades
y_proba

array([[0.1  , 0.89 , 0.01 ],
       [0.16 , 0.83 , 0.01 ],
       [0.3  , 0.65 , 0.05 ],
       ...,
       [0.025, 0.005, 0.97 ],
       [0.07 , 0.01 , 0.92 ],
       [0.025, 0.005, 0.97 ]])

## Resultados
Para poder entender mejor los resultados, vamos a crear una tabla de resultados

In [77]:
# resultados
resultados = pd.DataFrame()
resultados['fecha'] = fecha
resultados['hora'] = hora
resultados['Prediccion'] = y_pred
resultados['%pred: -1'] = y_proba[:,0]
resultados['%pred: 0'] = y_proba[:,1]
resultados['%pred: 1'] = y_proba[:,2]

resultados.head(10)

fecha   hora  Prediccion  %pred: -1  %pred: 0  %pred: 1
7  2022-01-03  10:21           0      0.100     0.890     0.010
8  2022-01-03  10:22           0      0.160     0.830     0.010
9  2022-01-03  10:23           0      0.300     0.650     0.050
10 2022-01-03  10:24           0      0.185     0.795     0.020
11 2022-01-03  10:25           0      0.065     0.855     0.080
12 2022-01-03  10:26           0      0.115     0.860     0.025
13 2022-01-03  10:27           0      0.060     0.885     0.055
14 2022-01-03  10:28           0      0.060     0.880     0.060
15 2022-01-03  10:29           0      0.065     0.810     0.125
16 2022-01-03  10:30           0      0.035     0.915     0.050

In [79]:
resultados.to_excel('RESULTADOS_ENERO2022.xlsx', index=False)

# fin